"use client";

import { useEffect, useState } from "react";
import { Modal, Field, PageHeader } from "../ui";
import { IconEdit, IconPlus, IconTrash } from "../icons";
import type { Role } from "@/db/schema";
import { PERMISSION_MODULES } from "@/lib/permissions";

type UserRow = { id: number; name: string; username: string; email: string | null; role: Role; active: number; createdAt: string };
const roles: { value: Role; label: string }[] = [{ value: "admin", label: "Administrateur" }, { value: "manager", label: "Manager" }, { value: "receptionist", label: "Réceptionniste" }, { value: "accountant", label: "Comptable" }, { value: "employee", label: "Employé" }];
const labels: Record<string, string> = { dashboard: "Tableau de bord", reservations: "Réservations", clients: "Clients", facturation: "Facturation", paiements: "Paiements", rapports: "Rapports", "user-management": "Gestion des utilisateurs", settings: "Paramètres", calendrier: "Calendrier", salles: "Salles", prestations: "Prestations", depenses: "Dépenses", "revenue-daily": "Recettes du jour", "revenue-history": "Historique des recettes", "audit-log": "Journal d’activité" };
const empty = { name: "", username: "", email: "", password: "", confirmPassword: "", role: "employee" as Role, active: true };

export default function UsersManagement() {
  const [users, setUsers] = useState<UserRow[]>([]); const [permissions, setPermissions] = useState<Record<string, string[]>>({});
  const [form, setForm] = useState(empty); const [editing, setEditing] = useState<UserRow | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const [u, r] = await Promise.all([fetch("/api/users"), fetch("/api/roles")]); if (u.ok) setUsers(await u.json()); if (r.ok) { const data = await r.json(); setPermissions(Object.fromEntries(data.roles.map((x: { role: string; permissions: string[] }) => [x.role, x.permissions]))); } };
  useEffect(() => {
    // Schedule after mount; the asynchronous request is the external system
    // that drives this state, rather than setting it during the effect itself.
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  const change = (key: keyof typeof empty, value: string | boolean) => setForm((f) => ({ ...f, [key]: value }));
  const showCreate = () => { setEditing(null); setForm(empty); setError(""); setOpen(true); };
  const showEdit = (u: UserRow) => { setEditing(u); setForm({ ...empty, name: u.name, username: u.username, email: u.email ?? "", role: u.role, active: u.active === 1 }); setError(""); setOpen(true); };
  async function save(e: React.FormEvent) { e.preventDefault(); setError(""); if (!editing && form.password !== form.confirmPassword) return setError("Les mots de passe ne correspondent pas."); if (!editing && form.password.length < 8) return setError("Le mot de passe doit contenir au moins 8 caractères."); setBusy(true); const payload = editing ? { name: form.name, email: form.email, role: form.role, active: form.active } : form; const res = await fetch(editing ? `/api/users/${editing.id}` : "/api/users", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setBusy(false); if (!res.ok) return setError((await res.json().catch(() => ({}))).error ?? "Enregistrement impossible."); setOpen(false); await load(); }
  async function remove(u: UserRow) { if (!confirm(`Supprimer le compte « ${u.username} » ?`)) return; const r = await fetch(`/api/users/${u.id}`, { method: "DELETE" }); if (!r.ok) alert((await r.json()).error ?? "Suppression impossible."); else await load(); }
  async function reset(u: UserRow) { const password = prompt(`Nouveau mot de passe pour ${u.username} (8 caractères minimum) :`); if (!password) return; const r = await fetch(`/api/users/${u.id}/reset-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!r.ok) alert((await r.json()).error ?? "Réinitialisation impossible."); else alert("Mot de passe réinitialisé."); }
  async function togglePermission(role: Role, module: string) { if (role === "admin") return; const current = permissions[role] ?? []; const next = current.includes(module) ? current.filter((x) => x !== module) : [...current, module]; const r = await fetch(`/api/roles/${role}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ permissions: next }) }); if (r.ok) setPermissions((p) => ({ ...p, [role]: next })); else alert((await r.json()).error ?? "Mise à jour impossible."); }
  return <div className="ef-fade"><PageHeader title="Gestion des utilisateurs" subtitle="Créez les comptes et gérez les accès par rôle." action={<button className="ef-btn ef-btn-primary" onClick={showCreate}><IconPlus className="h-4 w-4" /> Nouvel utilisateur</button>} />
    <div className="ef-card overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="border-b bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Nom complet</th><th>Identifiant</th><th>Email</th><th>Rôle</th><th>Statut</th><th>Créé le</th><th className="p-3">Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-b border-slate-100 last:border-0"><td className="p-3 font-semibold">{u.name}</td><td>{u.username}</td><td>{u.email || "—"}</td><td>{roles.find((r) => r.value === u.role)?.label}</td><td><span className={`ef-badge ${u.active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{u.active ? "Actif" : "Inactif"}</span></td><td>{new Date(u.createdAt).toLocaleDateString("fr-FR")}</td><td className="flex gap-1 p-3"><button title="Modifier" className="rounded p-1.5 text-slate-500 hover:bg-slate-100" onClick={() => showEdit(u)}><IconEdit className="h-4 w-4" /></button><button className="rounded px-2 py-1 text-xs text-amber-700 hover:bg-amber-50" onClick={() => reset(u)}>Mot de passe</button><button title="Supprimer" className="rounded p-1.5 text-red-500 hover:bg-red-50" onClick={() => remove(u)}><IconTrash className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>
    <section className="ef-card mt-6 p-5"><h2 className="text-base font-bold">Permissions par rôle</h2><p className="mb-4 text-sm text-slate-500">Les administrateurs ont toujours l’accès complet. Les changements s’appliquent à la prochaine connexion des utilisateurs concernés.</p><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-xs"><thead><tr><th className="p-2 text-left">Permission</th>{roles.map((r) => <th key={r.value} className="p-2 text-center">{r.label}</th>)}</tr></thead><tbody>{PERMISSION_MODULES.map((module) => <tr key={module} className="border-t border-slate-100"><td className="p-2 font-medium">{labels[module]}</td>{roles.map((r) => <td key={r.value} className="p-2 text-center"><input aria-label={`${labels[module]} ${r.label}`} type="checkbox" checked={r.value === "admin" || (permissions[r.value] ?? []).includes(module)} disabled={r.value === "admin"} onChange={() => void togglePermission(r.value, module)} /></td>)}</tr>)}</tbody></table></div></section>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Modifier l’utilisateur" : "Nouvel utilisateur"}><form className="space-y-3" onSubmit={save}><Field label="Nom complet"><input className="ef-input" value={form.name} onChange={(e) => change("name", e.target.value)} required /></Field><Field label="Identifiant"><input className="ef-input" value={form.username} disabled={!!editing} onChange={(e) => change("username", e.target.value)} required /></Field><Field label="Email (facultatif)"><input className="ef-input" type="email" value={form.email} onChange={(e) => change("email", e.target.value)} /></Field>{!editing && <><Field label="Mot de passe"><input className="ef-input" type="password" value={form.password} onChange={(e) => change("password", e.target.value)} required /></Field><Field label="Confirmer le mot de passe"><input className="ef-input" type="password" value={form.confirmPassword} onChange={(e) => change("confirmPassword", e.target.value)} required /></Field></>}<Field label="Rôle"><select className="ef-input" value={form.role} onChange={(e) => change("role", e.target.value)}>{roles.map((r) => <option key={r.value} value={r.value}>{r.label}</option>)}</select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => change("active", e.target.checked)} /> Compte actif</label>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="ef-btn ef-btn-ghost" onClick={() => setOpen(false)}>Annuler</button><button className="ef-btn ef-btn-primary" disabled={busy}>{busy ? "Enregistrement…" : "Enregistrer"}</button></div></form></Modal>
  </div>;
}
